use std::collections::HashMap;

use chrono::{DateTime, Utc};
use rust_decimal::prelude::ToPrimitive;
use serde::{Deserialize, Serialize};

use crate::domain::{Ticker, tickers::AssetType};

#[derive(Serialize, Deserialize, Default, Clone, Debug)]
pub struct TickerEntity {
    pub asset_type: AssetType,
    pub symbol: String,
    pub exchange: String,
    pub name: String,
    pub sector: Option<String>,
    pub industry: Option<String>,
    pub overview: String,

    pub total_assets: Option<i64>,
    pub eps: Option<f64>,
    pub pe_ratio: Option<f64>,
    pub peg_ratio: Option<f64>,
    pub pb_ratio: Option<f64>,
    pub ps_ratio: Option<f64>,
    pub forward_pe: Option<f64>,
    pub beta: Option<f64>,
    pub profit_margin: Option<f64>,
    pub operating_margin_ttm: Option<f64>,
    pub return_on_equity_ttm: Option<f64>,
    pub return_on_asset_ttm: Option<f64>,
    pub ebitda: Option<i64>,
    pub ev_to_revenue: Option<f64>,
    pub ev_to_ebitda: Option<f64>,
    pub shares_outstanding: Option<i64>,
    pub shares_float: Option<i64>,
    pub percent_insiders: Option<f64>,
    pub percent_institutions: Option<f64>,

    pub quarterly_earnings_growth_yoy: Option<f64>,
    pub quarterly_revenue_growth_yoy: Option<f64>,
    pub analyst_target_price: Option<f64>,
    pub analyst_rating_strong_buy: Option<i32>,
    pub analyst_rating_buy: Option<i32>,
    pub analyst_rating_hold: Option<i32>,
    pub analyst_rating_sell: Option<i32>,
    pub analyst_rating_strong_sell: Option<i32>,
    pub analyst_consensus: Option<String>,

    pub dividend_amt: f64,
    pub r#yield: f64,
    pub ex_div_date: Option<DateTime<Utc>>,
    pub pay_date: Option<DateTime<Utc>>,
    pub pay_ratio: f64,

    pub pr_date: Option<DateTime<Utc>>,

    pub pr_open: f64,
    pub pr_high: f64,
    pub pr_low: f64,
    pub pr_close: f64,
    pub pr_last: f64,
    pub pr_prev: f64,
    pub pr_diff_amt: f64,
    pub pr_diff_perc: f64,
    pub pr_diff_perc_search: f64,
    pub pr_52_wk_high: f64,
    pub pr_52_wk_low: f64,

    pub performance: HashMap<String, HashMap<String, f64>>,
    pub indicators: HashMap<String, f64>,
    pub avg_volume: i32,
    pub volume: i32,
}

impl From<Ticker> for TickerEntity {
    fn from(value: Ticker) -> Self {
        TickerEntity {
            asset_type: value.asset_type,
            symbol: value.symbol,
            exchange: value.exchange,
            name: value.name,
            sector: value.sector,
            industry: value.industry,
            overview: value.overview,
            total_assets: value.total_assets,
            eps: value.eps,
            pe_ratio: value.pe_ratio,
            peg_ratio: value.peg_ratio,
            pb_ratio: value.pb_ratio,
            ps_ratio: value.ps_ratio,
            forward_pe: value.forward_pe,
            beta: value.beta,
            profit_margin: value.profit_margin,
            operating_margin_ttm: value.operating_margin_ttm,
            return_on_equity_ttm: value.return_on_equity_ttm,
            return_on_asset_ttm: value.return_on_asset_ttm,
            ebitda: value.ebitda,
            ev_to_revenue: value.ev_to_revenue,
            ev_to_ebitda: value.ev_to_ebitda,
            shares_outstanding: value.shares_outstanding,
            shares_float: value.shares_float,
            percent_insiders: value.percent_insiders,
            percent_institutions: value.percent_institutions,
            quarterly_earnings_growth_yoy: value.quarterly_earnings_growth_yoy,
            quarterly_revenue_growth_yoy: value.quarterly_revenue_growth_yoy,
            analyst_target_price: value.analyst_target_price,
            analyst_rating_strong_buy: value.analyst_rating_strong_buy,
            analyst_rating_buy: value.analyst_rating_buy,
            analyst_rating_hold: value.analyst_rating_hold,
            analyst_rating_sell: value.analyst_rating_sell,
            analyst_rating_strong_sell: value.analyst_rating_strong_sell,
            analyst_consensus: value.analyst_consensus,
            dividend_amt: value.dividend_amt,
            r#yield: value.r#yield,
            ex_div_date: value.ex_div_date,
            pay_date: value.pay_date,
            pay_ratio: value.pay_ratio,
            pr_date: value.pr_date,
            pr_open: value.pr_open.to_f64().unwrap_or_default(),
            pr_high: value.pr_high.to_f64().unwrap_or_default(),
            pr_low: value.pr_low.to_f64().unwrap_or_default(),
            pr_close: value.pr_close.to_f64().unwrap_or_default(),
            pr_last: value.pr_last.to_f64().unwrap_or_default(),
            pr_prev: value.pr_prev.to_f64().unwrap_or_default(),
            pr_diff_amt: value.pr_diff_amt.to_f64().unwrap_or_default(),
            pr_diff_perc: value.pr_diff_perc.to_f64().unwrap_or_default(),
            pr_diff_perc_search: value.pr_diff_perc_search,
            pr_52_wk_high: value.pr_52_wk_high.to_f64().unwrap_or_default(),
            pr_52_wk_low: value.pr_52_wk_low.to_f64().unwrap_or_default(),
            performance: value.performance_search,
            indicators: value.indicators_search,
            avg_volume: value.avg_volume,
            volume: value.volume,
        }
    }
}
